main:
  push: 
    - runner: 
        cpus: 1
      imports: https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/github.yml
      stages:
        - name: ll
          script: ll
        - name: apt更新
          script: apt update
        - name: 安装必要依赖
          script: apt install sudo git wget curl -y
        - name: 安装Node.js
          script: sudo ./nodejs_install.sh
        - name: 同步至GitHub
          image: tencentcom/git-sync         
          settings:
            target_url: https://github.com/SDCOM-0415/Blog_buckup.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
            force: true
            branch: main 
            sync_mode: push