main:
  push: 
    - runner: 
        cpus: 1
      docker:
        image: node:20
      imports: 
        - https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/github.yml
        - https://cnb.cool/BlueScreen-Studio/Tech/secrets/-/blob/sdcom/gitcode.yml
      stages:
        - name: 查看文件目录
          script: ls
        - name: 清理历史文件
          script: rm -rf ./posts
        - name: apt更新
          script: apt update
        - name: 安装必要依赖
          script: apt install bash sudo git wget curl -y
        - name: 拉取wordpress-export-to-markdown
          script: git clone https://github.com/lonekorean/wordpress-export-to-markdown.git
        - name: 查看是否拉取成功
          script: ls -a
        - name: 执行转换Markdown操作
          script: npx wordpress-export-to-markdown --input=export.xml --post-folders=true --prefix-date=false --date-folders=none --save-images=all --output=./
        - name: git push
          script: 
            - git config --local user.email "q6hqAsJ89h3Z8U2eF6AK8D+SDCOM@noreply.cnb.cool"
            - git config --local user.name "SDCOM"
            - git add posts/
            - git commit -m "Updeta posts"
            - git push --force
        - name: 同步至GitHub
          image: tencentcom/git-sync         
          settings:
            target_url: https://github.com/SDCOM-0415/Blog_backup.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
            force: true
            branch: main 
            sync_mode: push
        - name: 同步至GitCode.com
          image: tencentcom/git-sync         
          settings:
            target_url: https://gitcode.com/SDCOM-0415/Blog_backup.git
            auth_type: https
            username: ${GIT_USER}
            password: ${GIT_TOKEN}
            git_user: ${GIT_USER}
            git_email: ${GITCODE_EMAIL}
            force: true
            branch: main 
            sync_mode: push